# Numpy

Why do we need numpy?

In [21]:
import time
import numpy as np

In [ ]:
x = np.random.random(100000000)

In [ ]:
start = time.time()
sum(x) / len(x)

print(time.time() - start)

13.078968286514282


In [ ]:
start = time.time()
np.mean(x)

print(time.time() - start)

0.25052595138549805


## Arange

In [16]:
np.random.random((3, 3))
np.random.randint(4, 15, (3, 3))

array([[ 6,  7, 11],
       [14,  9,  4],
       [ 8,  7, 12]])

In [5]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [11]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [15]:
np.linspace(0, 25, 5)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

### Distribution Function

In [24]:
np.random.normal(150, 5, (500, 500))

array([[157.40416028, 146.19940366, 147.78104218, ..., 154.49858232,
        150.07267373, 153.53491679],
       [155.75297563, 159.96509499, 155.58221074, ..., 152.6494646 ,
        151.78282347, 154.42242186],
       [143.64810622, 154.96526557, 148.0321363 , ..., 146.73079883,
        152.34160566, 146.07908011],
       ...,
       [148.97008091, 144.04820447, 149.03845155, ..., 152.62105019,
        150.49613128, 141.9628386 ],
       [158.14494661, 149.44450348, 150.06433569, ..., 153.71167747,
        142.96501584, 161.56792521],
       [144.12227945, 154.99926562, 146.11958141, ..., 151.16046053,
        150.44437346, 160.54373817]])

# Incerto

In [1]:
import numpy as np

In [18]:
x = np.zeros(10**5 -1)
x = np.append(x, 10**5)

In [26]:
std = x.std()

In [27]:
mad = (abs(x - x.mean())).sum() / 10**5

In [29]:
std / mad

158.11467358376333

In [30]:
np.pi / 2

1.5707963267948966